# -*- coding: utf-8 -*-
"""PyTorchMobile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Zbuu2BVXHB9hkLIZXUD6I4EC9-vzUf8
"""

# ========================================
# تحويل موديل Squat Classifier لـ PyTorch Mobile
# ========================================

import torch
import torch.nn as nn
from torch.utils.mobile_optimizer import optimize_for_mobile

# ========================
# 1. تعريف الموديل (نفس اللي استخدمته في التدريب)
# ========================
class SquatClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.proj = nn.Linear(198, 128)
        self.pos_emb = nn.Parameter(torch.randn(1, 128, 128))
        layer = nn.TransformerEncoderLayer(
            d_model=128, nhead=8, dim_feedforward=512,
            dropout=0.1, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(layer, num_layers=6)
        self.norm = nn.LayerNorm(128)
        self.head = nn.Linear(128, 2)

    def forward(self, x):
        x = self.proj(x) + self.pos_emb
        x = self.transformer(x)
        x = x.mean(dim=1)
        x = self.norm(x)
        return self.head(x)


# ========================
# 2. تحميل الموديل المدرّب
# ========================
DEVICE = torch.device('cpu')  # ⚠️ لازم CPU للتصدير!

model = SquatClassifier()
model.load_state_dict(torch.load('/content/BEST_SQUAT_MODEL.pth', map_location=DEVICE))
model.eval()

print("✅ الموديل اتحمّل بنجاح")


# ========================
# 3. تحويل لـ TorchScript باستخدام Tracing/Scripting
# ========================
# dummy input بنفس شكل الداتا (batch_size=1, seq_len=128, features=198)
dummy_input = torch.randn(1, 128, 198)

# تحويل الموديل لـ TorchScript باستخدام Scripting (أكثر مرونة للموديلات المعقدة)
print("🔄 جاري تحويل الموديل لـ TorchScript باستخدام Scripting...")
scripted_model = torch.jit.script(model)

# تحسين للموبايل (تقليل الحجم وزيادة السرعة)
print("⚡ تحسين الموديل للموبايل...")
optimized_model = optimize_for_mobile(scripted_model)


# ========================
# 4. حفظ الموديل للموبايل
# ========================
output_path = "squat_classifier_mobile.ptl"
optimized_model._save_for_lite_interpreter(output_path)

print(f"\n✅ تم التصدير بنجاح!")
print(f"📱 الملف: {output_path}")
import os
print(f"📦 الحجم: {os.path.getsize(output_path) / (1024*1024):.2f} MB")


# ========================
# 5. اختبار الموديل المُصدّر
# ========================
print("\n🧪 اختبار الموديل المُصدّر...")

# تحميل الموديل المحفوظ
loaded_model = torch.jit.load(output_path)
loaded_model.eval()

# تجربة Inference
test_input = torch.randn(1, 128, 198)
with torch.no_grad():
    output = loaded_model(test_input)
    prediction = output.argmax(1).item()
    confidence = torch.softmax(output, dim=1).max().item()

print(f"✅ الموديل شغّال!")
print(f"   Prediction: {'Perfect' if prediction == 0 else 'Shallow'}")
print(f"   Confidence: {confidence*100:.2f}%")


# ========================
# 6. معلومات الاستخدام على الموبايل
# ========================
print("\n" + "="*50)
print("📱 استخدام الموديل في Android:")
print("="*50)
print("""
1. أضف المكتبة في build.gradle:
   implementation 'org.pytorch:pytorch_android_lite:1.13.1'
   implementation 'org.pytorch:pytorch_android_torchvision_lite:1.13.1'

2. ضع الملف squat_classifier_mobile.ptl في:
   app/src/main/assets/

3. كود Java/Kotlin:

   // تحميل الموديل
   Module module = LiteModuleLoader.load(
       assetFilePath(this, "squat_classifier_mobile.ptl")
   );

   // تحضير الـ input (128 frames × 198 features)
   float[] inputArray = new float[128 * 198];
   // ... ملي الـ array بالداتا ...

   Tensor inputTensor = Tensor.fromBlob(
       inputArray,
       new long[]{1, 128, 198}
   );

   // Inference
   Tensor outputTensor = module.forward(
       IValue.from(inputTensor)
   ).toTensor();

   float[] scores = outputTensor.getDataAsFloatArray();
   int prediction = scores[0] > scores[1] ? 0 : 1;
   // 0 = Perfect, 1 = Shallow
""")

print("\n" + "="*50)
print("📱 استخدام الموديل في iOS (Swift):")
print("="*50)
print("""
1. أضف المكتبة عبر CocoaPods:
   pod 'LibTorch-Lite', '~>1.13.0'

2. ضع الملف في Xcode project

3. كود Swift:

   // تحميل الموديل
   guard let modelPath = Bundle.main.path(
       forResource: "squat_classifier_mobile",
       ofType: "ptl"
   ) else { return }

   let module = try! TorchModule(fileAtPath: modelPath)

   // تحضير input
   var inputArray = [Float](repeating: 0, count: 128 * 198)
   // ... ملي الـ array ...

   let inputTensor = try! TorchTensor(
       shape: [1, 128, 198],
       data: &inputArray
   )

   // Inference
   let output = try! module.forward([inputTensor])
   let scores = output[0].floatArray
   let prediction = scores[0] > scores[1] ? 0 : 1
""")

print("\n✨ تم! الموديل جاهز للاستخدام على الموبايل ✨")