import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  String _language = 'en';

  final Map<String, Map<String, String>> translations = {
    'en': {
      'appName': 'AI Fitness Coach',
      'login': 'Login',
      'signUp': 'Sign Up',
      'email': 'Email',
      'phone': 'Phone',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot your password?',
      'createAccount': 'Create New Account',
      'fullName': 'Full Name',
      'male': 'Male',
      'female': 'Female',
      'gender': 'Gender',
      'height': 'Height',
      'weight': 'Weight',
      'selectGoal': 'Select Your Goal',
      'loseFat': 'Lose Fat',
      'gainWeight': 'Gain Weight',
      'buildMuscle': 'Build Muscle',
      'improveFitness': 'Improve Fitness',
      'activityLevel': 'Activity Level',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'equipment': 'Available Equipment',
      'home': 'Home',
      'gym': 'Gym',
      'startPlan': 'Start My Plan',
      'hello': 'Hello',
      'todayExercises': "Today's Exercises",
      'todayMeals': "Today's Meals",
      'exercises': 'Exercises',
      'nutrition': 'Nutrition',
      'progress': 'Progress',
      'settings': 'Settings',
      'aiCoach': 'AI Coach',
      'sets': 'Sets',
      'reps': 'Reps',
      'rest': 'Rest',
      'startExercise': 'Start Exercise',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snack': 'Snack',
      'calories': 'Calories',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'viewRecipe': 'View Recipe',
      'weightChart': 'Weight Progress',
      'muscleGain': 'Muscle Gain',
      'daysCompleted': 'Days Completed',
      'achievements': 'Achievements',
      'editProfile': 'Edit Profile',
      'changeGoal': 'Change Goal',
      'notifications': 'Notifications',
      'privacy': 'Privacy & Terms',
      'logout': 'Logout',
      'next': 'Next',
      'skip': 'Skip',
      'stop': 'Stop',
      'age': 'Age',
      'cm': 'cm',
      'kg': 'kg',
      'welcomeBack': 'Welcome Back',
      'continueYourJourney': 'Continue your fitness transformation',
      'physicalStats': 'Physical Stats',
      'helpUs': 'Help us personalize your plan',
      'startYourJourney': 'Start Your Journey',
      'transformYourBody': 'Transform your body, transform your life',
      'goodDay': 'Good day,',
      'healthyBody': 'healthy body',
      'youAreDoing': "You're doing great this week. Keep pushing forward!",
      'workouts': 'Workouts',
      'trainingPrograms': 'Training Programs',
      'seeAll': 'See all',
      'fullBodyBlast': 'Full Body Blast',
      'chestTriceps': 'Chest & Triceps',
      'cardioHIIT': 'Cardio HIIT',
    },
    'ar': {
      'appName': 'مدرب اللياقة الذكي',
      'login': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'password': 'كلمة المرور',
      'confirmPassword': 'تأكيد كلمة المرور',
      'forgotPassword': 'هل نسيت كلمة المرور؟',
      'createAccount': 'إنشاء حساب جديد',
      'fullName': 'الاسم الكامل',
      'male': 'ذكر',
      'female': 'أنثى',
      'gender': 'الجنس',
      'height': 'الطول',
      'weight': 'الوزن',
      'selectGoal': 'حدد هدفك',
      'loseFat': 'خسارة الدهون',
      'gainWeight': 'زيادة الوزن',
      'buildMuscle': 'بناء العضلات',
      'improveFitness': 'تحسين اللياقة',
      'activityLevel': 'مستوى النشاط',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'equipment': 'المعدات المتاحة',
      'home': 'المنزل',
      'gym': 'الجيم',
      'startPlan': 'ابدأ خطتي',
      'hello': 'مرحبا',
      'todayExercises': 'تمارين اليوم',
      'todayMeals': 'وجبات اليوم',
      'exercises': 'التمارين',
      'nutrition': 'التغذية',
      'progress': 'التقدم',
      'settings': 'الإعدادات',
      'aiCoach': 'مدرب ذكي',
      'sets': 'مجموعات',
      'reps': 'تكرارات',
      'rest': 'راحة',
      'startExercise': 'ابدأ التمرين',
      'breakfast': 'الإفطار',
      'lunch': 'الغداء',
      'dinner': 'العشاء',
      'snack': 'وجبة خفيفة',
      'calories': 'السعرات الحرارية',
      'protein': 'البروتين',
      'carbs': 'الكربوهيدرات',
      'viewRecipe': 'عرض الوصفة',
      'weightChart': 'تقدم الوزن',
      'muscleGain': 'زيادة العضلات',
      'daysCompleted': 'أيام مكتملة',
      'achievements': 'الإنجازات',
      'editProfile': 'تعديل الملف الشخصي',
      'changeGoal': 'تغيير الهدف',
      'notifications': 'الإخطارات',
      'privacy': 'الخصوصية والشروط',
      'logout': 'تسجيل الخروج',
      'next': 'التالي',
      'skip': 'تخطي',
      'stop': 'إيقاف',
      'age': 'العمر',
      'cm': 'سم',
      'kg': 'كغ',
      'welcomeBack': 'أهلا وسهلا',
      'continueYourJourney': 'استمر في رحلة لياقتك البدنية',
      'physicalStats': 'إحصائياتك البدنية',
      'helpUs': 'ساعدنا في تخصيص خطتك',
      'startYourJourney': 'ابدأ رحلتك',
      'transformYourBody': 'حول جسدك، حول حياتك',
      'goodDay': 'يوم جميل،',
      'healthyBody': 'جسم صحي',
      'youAreDoing': 'أنت تقوم بعمل رائع هذا الأسبوع. استمر في المحاولة!',
      'workouts': 'تمارين',
      'trainingPrograms': 'برامج التدريب',
      'seeAll': 'عرض الكل',
      'fullBodyBlast': 'تفجير الجسم كاملاً',
      'chestTriceps': 'الصدر والعضلة ثلاثية',
      'cardioHIIT': 'تمرين عالي الكثافة',
    },
  };

  String get language => _language;
  bool get isRTL => _language == 'ar';

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  String t(String key) {
    return translations[_language]?[key] ?? key;
  }
}
